#!/bin/bash
#SBATCH --job-name=benchmark_ood_automl
#SBATCH --time=2:00:00 --mem=488G
#SBATCH --ntasks=1 --nodes=1 --cpus-per-task=96
#SBATCH --output=out --error=error
#SBATCH --partition=pvc
#SBATCH --gres=gpu:pvc:2
#SBATCH --exclusive


module purge
cd /scratch/user/u.ks124812/XGBoost_Benchmark
source modules.sh
source venv/bin/activate
cd /scratch/user/u.ks124812/TLC-Trip-Record-Data-Scripts
#python3 combine.py
python3 preprocess.py
